# Generated by Django 3.2.5 on 2021-07-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Dead', 'Dead'), ('Alive', 'Alive'), ('Unknown', 'Unknown')], max_length=15)),
                ('species', models.CharField(max_length=255)),
                ('character_type', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Genderless', 'Genderless'), ('Unknown', 'Unknown')], max_length=15)),
                ('origin', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
