# Generated by Django 3.2.5 on 2021-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_character_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='character_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='gender',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
