# Generated by Django 3.2.5 on 2021-07-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210724_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='id',
            new_name='character_id',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='character_type',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
